title: Paul Sava
description: Personal website
repository: paulsava/paulsava.github.io
baseurl: ""
url: "https://paulsava.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Include these files in the build
include:
  - publications.md
  - projects.md
  - blog.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 