title: Paul Sava
description: Personal website
repository: paulsava/paulsava.github.io
baseurl: ""
url: "https://paulsava.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:year/:title
  projects:
    output: true
    permalink: /projects/:title
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 