title: Paul Sava
description: Personal website
repository: paulsava/paulsava.github.io
baseurl: ""
url: "https://paulsava.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Include these files in the build
include:
  - _pages
  - blog.md
  - projects.md
  - publications.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: "pages" # limit to pages
    values:
      layout: "default" 