name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: node build.js

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages

      - name: Set up Python
        if: github.ref == 'refs/heads/main'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        if: github.ref == 'refs/heads/main'
        run: |
          python -m pip install --upgrade pip
          pip install markdown

      - name: Generate RSS Feed
        if: github.ref == 'refs/heads/main'
        run: python scripts/generate_rss.py 